name: CI-Pipeline

permissions:
  contents: read
  issues: write
  id-token: write

on:
  push:
    branches:
      - "main"

jobs:
    pipeline:
     runs-on: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
